- name: DevOps Linux Stage 1
  hosts: all
  gather_facts: true
  strategy: free
  vars:
    setup_facts: "{{ lookup('file','../setup.yml') | from_yaml }}"
  tasks:
    - name: Print ansible facts
      debug:
        var: ansible_facts
        verbosity: 2
    - name: Print setup config
      debug:
        var: setup_facts
        verbosity: 2
    - name: First boot
      include_role:
        name: firstboot
